import Config

config :fahrgastrechte,
  secure_session_cookie: false,
  development_login: true,
  development_identity: %{
    issuer: "https://development.invalid/application/fahrgastrechte",
    subject: "local-developer",
    email: "entwicklung@example.invalid",
    display_name: "Lokale Entwicklung"
  }

# Configure your database
config :fahrgastrechte, Fahrgastrechte.Repo,
  username: System.get_env("DATABASE_USER", "postgres"),
  password: System.get_env("DATABASE_PASSWORD", "postgres"),
  hostname: System.get_env("DATABASE_HOST", "localhost"),
  port: String.to_integer(System.get_env("DATABASE_PORT", "5432")),
  database: System.get_env("DATABASE_NAME", "fahrgastrechte_dev"),
  template: System.get_env("DATABASE_TEMPLATE", "template0"),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :fahrgastrechte, FahrgastrechteWeb.Endpoint,
  # Listen on every IPv4 interface so the development server is reachable from the LAN.
  http: [ip: {0, 0, 0, 0}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "FucssFHQoF6CwRM1GB23TcJBKRWSQBMXUgd26EhSM+NO0Kxxd/AO81gOrR5JF/o4",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:fahrgastrechte, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:fahrgastrechte, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable the LiveDashboard development route.
config :fahrgastrechte, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
